"""Generate ``dbt/models/staging/_sources.yml`` from EKOS's compiled knowledge.

For every table EKOS Migrate loaded into ``lsmb_raw``, this asks EKOS (``ekos_state``, logged in
``logs/ekos_queries.jsonl``) for the table and column descriptions it recovered from LedgerSMB's own
``COMMENT ON`` statements, each with the file and line it came from. It merges those with the
columns actually **deployed** in ClickHouse (``system.columns``), so the documentation describes the
table as it exists, not as the repository's base DDL declared it.

A deployed column EKOS has no description for is marked as such, rather than given an invented one.
That usually means a later LedgerSMB schema change added it (the drift ``ekos migrate discover``
reported).

Run:  .venv/bin/python pipelines/docs/gen_dbt_sources.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "pipelines"))
from ekos_log import EkosMcp  # noqa: E402
from lsmb_pipelines.config import clickhouse  # noqa: E402

OUT = ROOT / "dbt" / "models" / "staging" / "_sources.yml"


def yaml_str(s: str) -> str:
    """A YAML double-quoted scalar, single line."""
    s = " ".join(s.split())
    return json.dumps(s, ensure_ascii=False)


def table_id(mcp: EkosMcp, table: str) -> str | None:
    ans = mcp.call(
        "ekos_ekl",
        {"query": f"FIND Object WHERE kind = 'Table' AND name = '{table}'"},
        f"dbt docs: locate `{table}`",
    )
    rows = ans.get("rows", []) if isinstance(ans, dict) else []
    return rows[0]["id"] if rows else None


def main() -> None:
    ch = clickhouse()
    deployed: dict[str, list[tuple[str, str]]] = {}
    for table, col, typ in ch.query(
        "SELECT table, name, type FROM system.columns WHERE database = 'lsmb_raw' "
        "ORDER BY table, position"
    ).result_rows:
        deployed.setdefault(table, []).append((col, typ))

    mcp = EkosMcp("8-documentation")
    lines = [
        "# GENERATED by pipelines/docs/gen_dbt_sources.py from EKOS's compiled knowledge of the",
        "# LedgerSMB sources (ekos_state → COMMENT ON evidence) merged with the columns deployed in",
        "# ClickHouse. Do not edit by hand; re-run the generator.",
        "version: 2",
        "",
        "sources:",
        "  - name: lsmb_raw",
        "    database: lsmb_raw",
        "    schema: lsmb_raw",
        "    description: >",
        "      LedgerSMB tables loaded from PostgreSQL by EKOS Migrate (RFC 0160) and validated",
        "      V1/V2/V3 (RFC 0156) — row counts, per-column aggregates and bucketed row hashes.",
        "      `tax` is loaded by pipelines/lsmb_pipelines/load_tax.py (see its docstring).",
        "    loaded_at_field: null",
        "    tables:",
    ]
    stats = {"tables": 0, "columns": 0, "described_by_ekos": 0}
    try:
        for table in sorted(deployed):
            tid = table_id(mcp, table)
            state = (
                mcp.call("ekos_state", {"id": tid}, f"dbt docs: descriptions of `{table}`")
                if tid
                else {}
            )
            obj = state.get("object", {}) if isinstance(state, dict) else {}
            evidence = state.get("evidence", []) if isinstance(state, dict) else []
            table_comment = next(
                (
                    e["fragment"].split(" IS ", 1)[1]
                    for e in evidence
                    if e.get("fragment", "").startswith(f"COMMENT ON TABLE {table} IS ")
                ),
                None,
            )
            where = next(
                (
                    f"{e['location']['path']}:{e['location'].get('line') or ''}".rstrip(":")
                    for e in evidence
                    if e.get("fragment", "").startswith(f"CREATE TABLE {table}")
                ),
                "sql/Pg-database.sql",
            )
            col_desc = {
                c["name"]: c["description"]
                for c in (obj.get("properties", {}) or {}).get("columns", [])
                if c.get("description")
            }
            desc = table_comment or f"LedgerSMB table `{table}` (no table comment in the sources)."
            lines += [
                f"      - name: {table}",
                f"        description: {yaml_str(desc + f' [EKOS: defined in {where}]')}",
                "        columns:",
            ]
            stats["tables"] += 1
            for col, typ in deployed[table]:
                stats["columns"] += 1
                if col in col_desc:
                    stats["described_by_ekos"] += 1
                    d = f"{col_desc[col]} [EKOS: COMMENT ON COLUMN] ClickHouse type {typ}."
                else:
                    d = (
                        f"ClickHouse type {typ}. No description in LedgerSMB's sources — typically "
                        "added by a later schema change (see ekos migrate discover drift)."
                    )
                lines += [f"          - name: {json.dumps(col)}", f"            description: {yaml_str(d)}"]
    finally:
        mcp.close()

    OUT.write_text("\n".join(lines) + "\n")
    print(json.dumps(stats))


if __name__ == "__main__":
    main()
