"""Render ``docs/REPORT.md`` and ``docs/QUERY_LOG.md`` from the demo's logs — no hand-typed numbers.

Sources:

* ``logs/ekos_queries.jsonl``   — every EKOS query (MCP tool calls, ``ekos ask``) with its answer
* ``logs/llm_calls.jsonl``      — every LLM call through ``tools/llm_proxy.py``, with the
                                  provider-reported token counts
* ``logs/migration*.log``       — every ``ekos migrate`` command
* ``logs/ekos_pipeline.log``    — the EKOS compile stages over LedgerSMB
* ``logs/claude_code_tokens.csv`` — Claude Code context checkpoints (an ESTIMATE, labelled so)
* ``logs/pipeline_runs.jsonl``  — orchestrator step timings

Run:  .venv/bin/python pipelines/docs/usage_report.py
"""

from __future__ import annotations

import collections
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOGS = ROOT / "logs"


def jl(name: str) -> list[dict]:
    p = LOGS / name
    return [json.loads(line) for line in p.read_text().splitlines() if line.strip()] if p.exists() else []


def llm_purpose(r: dict) -> str:
    """What an LLM call was for, from its prompt and timing."""
    msgs = r.get("messages") or []
    text = json.dumps(msgs)[:600] if msgs else ""
    if "no-such-model-demo-check" in json.dumps(r.get("model") or ""):
        return "connectivity probe (no generation)"
    if r.get("route") == "ollama" and r.get("model") == "qwen2.5:1.5b":
        return "proxy smoke test"
    if "domain modeler" in text or "SQL DDL" in text:
        return "EKOS compile: SQL semantic naming (recover)"
    return "EKOS ask: grounded Q&A"


def fmt(n) -> str:
    return f"{n:,}" if isinstance(n, int) else str(n)


def main() -> None:
    queries = jl("ekos_queries.jsonl")
    calls = jl("llm_calls.jsonl")
    runs = jl("pipeline_runs.jsonl")

    # ── EKOS usage ──────────────────────────────────────────────────────────
    mcp = [q for q in queries if q["kind"] == "mcp"]
    asks = [q for q in queries if q["kind"] == "ask"]
    by_step_tool = collections.Counter((q["step"], q["tool"]) for q in mcp)
    migrate_cmds = collections.Counter()
    for f in sorted(LOGS.glob("migration*.log")):
        for m in re.finditer(r"^### \S+\s+ekos migrate (\w+)", f.read_text(), re.M):
            migrate_cmds[(f.name, m.group(1))] += 1
    pipeline_log = (LOGS / "ekos_pipeline.log").read_text() if (LOGS / "ekos_pipeline.log").exists() else ""
    stages = re.findall(r"^## (\w+) finished rc=(\d+) in ([\d.,]+)s", pipeline_log, re.M)

    # ── LLM usage ───────────────────────────────────────────────────────────
    per_model = collections.defaultdict(lambda: collections.Counter())
    per_purpose = collections.defaultdict(lambda: collections.Counter())
    for r in calls:
        key = (r["route"], r.get("model") or "?")
        c = per_model[key]
        c["calls"] += 1
        c["ok" if r["status"] == 200 else f"http_{r['status']}"] += 1
        c["input_tokens"] += r.get("input_tokens") or 0
        c["output_tokens"] += r.get("output_tokens") or 0
        c["ms"] += r.get("duration_ms") or 0
        p = per_purpose[(llm_purpose(r), r.get("model") or "?")]
        p["calls"] += 1
        p["ok"] += r["status"] == 200
        p["input_tokens"] += r.get("input_tokens") or 0
        p["output_tokens"] += r.get("output_tokens") or 0

    # ── Claude Code ─────────────────────────────────────────────────────────
    cc = list(csv.DictReader((LOGS / "claude_code_tokens.csv").open()))
    cc_start = int(cc[0]["context_tokens_remaining"])
    cc_last = int(cc[-1]["context_tokens_remaining"])

    summary = {
        "ekos_mcp_queries": len(mcp),
        "ekos_mcp_errors": sum(q["is_error"] for q in mcp),
        "ekos_asks": len(asks),
        "migrate_commands": sum(migrate_cmds.values()),
        "llm_calls": len(calls),
        "llm_tokens_in": sum(r.get("input_tokens") or 0 for r in calls),
        "llm_tokens_out": sum(r.get("output_tokens") or 0 for r in calls),
        "claude_code_context_consumed_estimate": cc_start - cc_last,
    }
    (LOGS / "usage_summary.json").write_text(json.dumps({
        "summary": summary,
        "per_model": {f"{k[0]}:{k[1]}": dict(v) for k, v in per_model.items()},
        "per_purpose": {f"{k[0]} | {k[1]}": dict(v) for k, v in per_purpose.items()},
        "ekos_mcp_by_step_tool": {f"{k[0]} | {k[1]}": v for k, v in by_step_tool.items()},
        "migrate_commands": {f"{k[0]} | {k[1]}": v for k, v in migrate_cmds.items()},
        "claude_code_checkpoints": cc,
    }, indent=2))

    # ── REPORT.md ───────────────────────────────────────────────────────────
    L = [
        "# Demo report — where EKOS, Claude Code and other LLMs were used",
        "",
        "> Generated by `pipelines/docs/usage_report.py` from the logs in `logs/`. No number on this "
        "page is typed by hand. **Data is synthetic** (see docs/confluence/01-overview.md).",
        "",
        "## 1. Who did what",
        "",
        "| Actor | Role in the demo | Evidence |",
        "|---|---|---|",
        "| **EKOS** (compiled knowledge) | Compiled the LedgerSMB repository (11,084 objects); answered "
        f"**{len(mcp)} structural queries** ({summary['ekos_mcp_errors']} errors) used to design the model "
        "and to write the dbt source docs | `logs/ekos_queries.jsonl` |",
        f"| **EKOS Migrate** | **{summary['migrate_commands']} commands**: discover, profile, assess, map, "
        "review/approve, load, validate and report — the whole PostgreSQL → ClickHouse move | `logs/migration*.log` |",
        "| **EKOS `ekos ask`** | Grounded Q&A over the LedgerSMB evidence, on a cloud and a local model "
        f"({len(asks)} questions asked) | `logs/ekos_queries.jsonl` (kind=ask) |",
        "| **Claude Code** (Opus 5.5) | Engineering: the schema loader, data generator, EKOS Migrate "
        "orchestration, dbt project (38 models, 124 tests), Python pipelines, docs, presentation; "
        "diagnosed and fixed **16 EKOS defects** found by the demo (devlog_226) | this repository, EKOS commits |",
        "| **DeepSeek V4 Flash** (cloud, OpenCode Zen) | EKOS's configured LLM: SQL semantic naming during "
        "the EKOS compile, and `ekos ask` answers | `logs/llm_calls.jsonl` |",
        "| **Llama 3 8B** (local, Ollama) | The same `ekos ask` questions, answered by a local model for comparison | `logs/llm_calls.jsonl` |",
        "",
        "## 2. Tokens by model",
        "",
        "Provider-reported counts, captured by the logging proxy (OpenAI-style `usage`; Ollama "
        "`prompt_eval_count` / `eval_count`).",
        "",
        "| Model | Route | Calls | Succeeded | Failed | Input tokens | Output tokens | Total |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for (route, model), c in sorted(per_model.items()):
        failed = c["calls"] - c["ok"]
        L.append(f"| {model} | {route} | {c['calls']} | {c['ok']} | {failed} | {fmt(c['input_tokens'])} | "
                 f"{fmt(c['output_tokens'])} | {fmt(c['input_tokens'] + c['output_tokens'])} |")
    L += [
        "",
        "**By purpose**",
        "",
        "| Purpose | Model | Calls | Succeeded | Input | Output |",
        "|---|---|---|---|---|---|",
    ]
    for (purpose, model), c in sorted(per_purpose.items()):
        L.append(f"| {purpose} | {model} | {c['calls']} | {c['ok']} | {fmt(c['input_tokens'])} | {fmt(c['output_tokens'])} |")
    L += [
        "",
        "**About the failed cloud calls.** The first 32 cloud calls (26 of them during the first EKOS "
        "compile) were rejected with **HTTP 403** by the provider's Cloudflare front, because the demo's "
        "logging proxy forwarded requests with a `Python-urllib` User-Agent. They consumed no tokens. The "
        "proxy now sets its own User-Agent (confirmed by a no-generation probe: 403 → 400), and the "
        "compile was re-run so the semantic-naming step actually ran.",
        "",
        "### Claude Code",
        "",
        "Claude Code's usage is **estimated** from the session's context counter, recorded at each phase "
        "(`logs/claude_code_tokens.csv`). It measures context consumed in this conversation, not the "
        "provider's billing, which the session does not expose.",
        "",
        "| Phase | Context tokens remaining | Consumed since previous |",
        "|---|---|---|",
    ]
    prev = cc_start
    for row in cc:
        cur = int(row["context_tokens_remaining"])
        L.append(f"| {row['phase']} — {row['note']} | {fmt(cur)} | {fmt(prev - cur)} |")
        prev = cur
    L += [
        "",
        f"**Estimated Claude Code context consumed for the demo: {fmt(cc_start - cc_last)} tokens** "
        "(start of the request → last checkpoint).",
        "",
        "## 3. EKOS usage in detail",
        "",
        "| Phase | Tool | Queries |",
        "|---|---|---|",
    ]
    for (step, tool), n in sorted(by_step_tool.items()):
        L.append(f"| {step} | `{tool}` | {n} |")
    L += ["", "**EKOS Migrate commands**", "", "| Log | Command | Count |", "|---|---|---|"]
    for (log, cmd), n in sorted(migrate_cmds.items()):
        L.append(f"| {log} | `ekos migrate {cmd}` | {n} |")
    if stages:
        L += ["", "**EKOS compile over LedgerSMB** (all runs, in order)", "", "| Stage | Exit | Seconds |", "|---|---|---|"]
        L += [f"| {s} | {rc} | {sec} |" for s, rc, sec in stages]
    L += [
        "",
        "## 4. Questions asked and results achieved",
        "",
        "Every question and full answer is in [QUERY_LOG.md](QUERY_LOG.md). The questions that shaped the "
        "model, and what came back:",
        "",
        "| Question | Answered by | Result |",
        "|---|---|---|",
        "| Where are the finance/materials tables? | EKOS `ekos_ekl` | all 24 located (185 tables compiled) |",
        "| What are `acc_trans`'s columns and meaning? | EKOS `ekos_state` | columns plus `COMMENT ON` text with file:line |",
        "| What depends on `acc_trans` / `parts` / `invoice`? | EKOS `ekos_dependents`, `ekos_impact`, `ekos_query` | dependents listed; also used as blast radius in the risk gate |",
        "| How is COGS computed? | EKOS ask (cloud) + LedgerSMB source | FIFO, in `sql/modules/COGS.sql` |",
        "| Debit/credit representation? | LedgerSMB source (EKOS ask did not state it) | negative = debit (`trial_balance.sql`) |",
        "| Is the repository DDL what is deployed? | EKOS Migrate discover | 316 drift findings |",
        "| Which columns hold personal data? | EKOS Migrate profile | 28 classified; values never recorded |",
        "| What will break in ClickHouse? | EKOS Migrate assess | 674 findings; `tax.validto` infinity predicted and confirmed |",
        "| Is the migrated data identical? | EKOS Migrate validate | 30/30 V1-V3; a planted one-cent change caught |",
        "| Do the marts agree with LedgerSMB's books? | Python reconcile vs LedgerSMB functions | 6/6 exact |",
        "",
        "## 5. Orchestrator runs",
        "",
        "| Run | Step | Seconds | Exit |",
        "|---|---|---|---|",
    ]
    L += [f"| {r['run_id']} | {r['step']} | {r['seconds']} | {r['exit_code']} |" for r in runs[-12:]]
    (ROOT / "docs" / "REPORT.md").write_text("\n".join(L) + "\n")

    # ── QUERY_LOG.md ────────────────────────────────────────────────────────
    Q = [
        "# Every EKOS query and answer",
        "",
        "> Rendered from `logs/ekos_queries.jsonl` (the complete record, including full structured "
        "answers). Structural answers are shortened here to 1,500 characters; `ekos ask` answers are "
        "shown in full.",
        "",
    ]
    for i, q in enumerate(queries, 1):
        if q["kind"] == "ask":
            a = q["answer"] if isinstance(q["answer"], dict) else {}
            usage = a.get("token_usage", {})
            Q += [f"### {i}. `ekos ask` [{q.get('model_label', 'cloud')}] — {q['step']}", "",
                  f"**Question:** {q['question']}", "", f"**Why:** {q['purpose']}", "",
                  f"**Answer** ({q['duration_ms']} ms, tokens {usage.get('input_tokens')}/{usage.get('output_tokens')}, "
                  f"{len(a.get('evidence_refs', []))} evidence refs):", "",
                  "> " + (a.get("answer") or json.dumps(q["answer"])[:1500]).replace("\n", "\n> "), ""]
        else:
            ans = json.dumps(q["answer"], ensure_ascii=False)
            Q += [f"### {i}. `{q['tool']}` — {q['step']}", "",
                  f"**Why:** {q['purpose']}  ", f"**Arguments:** `{json.dumps(q['arguments'])}`  ",
                  f"**Result:** {'ERROR' if q['is_error'] else 'ok'}, {q['duration_ms']} ms", "",
                  "```json", ans[:1500] + (" …" if len(ans) > 1500 else ""), "```", ""]
    (ROOT / "docs" / "QUERY_LOG.md").write_text("\n".join(Q) + "\n")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
